import * as React from 'react'
import Footer from '../components/footer/footer'
import Header from '../components/header/header'
import { Helmet } from 'react-helmet'

type Props = {
	children: React.ReactNode
	title: string
}

export default function Layout({ children, title }: Props) {
	return (
		<>
			<Helmet>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Helmet>
			<div className='page'>
				<Header />
				{children}
				<Footer />
			</div>
		</>
	)
}
